sudo: required
services:
  - docker

script:
  - docker build -t i321174/node .
  - docker images i321174/node

before_deploy:
  - docker login -u i321174 -p Kaash123

deploy:
  provider: script
  script: docker push i321174/node
  on:
    branch: master